# Generated by Django 3.1.7 on 2021-03-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default=1, help_text='Description Task', verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=False, help_text='Status Task', verbose_name='status'),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='f', help_text='Title Task', max_length=200, unique=True, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(help_text='ID Task', primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
    ]
